Repository SagnikDeshmukh/MAKAUT_Organiser, pull requests merged in 2023-10, with the labels that each got.

#27 Added the Tech Implementation
  Tech Imp.txt
  index.html
  index.js
  style.css
Labels: documentation, help wanted, good first issue, hacktoberfest

#28 feature:about section added
  Resources/about-pdf.jpg
  Resources/hero-2.jpg
  Resources/hero-man.png
  index.html
Labels: hacktoberfest

#30 fix: remove unsuitable text
  index.html
Labels: hacktoberfest

#31 add:selection page added
  index.html
Labels: enhancement, hacktoberfest
